### ISSUE TITLE
Map tiles are not displayed anymore

### ISSUE THREAD

**Issue by Rudloff** [westnordost/StreetComplete#1348]
For a few days/weeks, the map has not been loading correctly.
It loads very slowly at lower zoom levels and does not load at all at higher zoom levels.

I can see errors like this in logcat:
```
03-04 12:41:36.125  9636  9727 D Tangram : ERROR networkDataSource.cpp:70: Error for URL request 'https://tiles.map-data.de/vector/v1/512/all/16/33329/22046.mvt': INTERNAL SERVER ERROR
03-04 12:41:36.125  9636  9727 D OkHttp  : Callback failure for call to https://tiles.map-data.de/...
03-04 12:41:36.125  9636  9727 D OkHttp  : java.io.IOException: Unexpected response code: Response{protocol=http/1.1, code=500, message=INTERNAL SERVER ERROR, url=https://tiles.map-data.de/vector/v1/512/all/16/33329/22046.mvt?api_key=null} for URL: https://tiles.map-data.de/vector/v1/512/all/16/33329/22046.mvt
03-04 12:41:36.125  9636  9727 D OkHttp  : 	at com.mapzen.tangram.MapController$13.onResponse(MapController.java:1388)
03-04 12:41:36.125  9636  9727 D OkHttp  : 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
03-04 12:41:36.126  9636  9727 D OkHttp  : 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-04 12:41:36.126  9636  9727 D OkHttp  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-04 12:41:36.126  9636  9727 D OkHttp  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-04 12:41:36.126  9636  9727 D OkHttp  : 	at java.lang.Thread.run(Thread.java:761)
```

**How to Reproduce**
Install the app from F-Droid, open it and zoom on some city.

(I also tried to clear the app data but it did not fix it.)

**Versions affected**
StreetComplete 10.2 on Android 7.1.2

**Comment by Akasch** [comment]
I think I have identified the problem. I have to make a new import of the region. Is it correct that [this Region](https://a.tile.openstreetmap.org/6/32/21.png) is the one with problems?

The Import will take some hours, I write once it is finished

**Comment by Rudloff** [comment]
Yes, I am in this region. (Sorry, I tried to check if it worked in cities around me, but did not think to try in a distant country.)

**Comment by Akasch** [comment]
The import is running, but I think it will need between 2 and 5 hours to finish. (As a side effect you get a updated  map from 4 days ago)

Whats ok. I am currently under way to use multiple smaller databases, so it more easy to handle. But normally a user should not notice the borders.

**Comment by westnordost** [comment]
👍 

How about posting on the mailing list, forum and/or wiki about this distributed vector tile server when this is ready with instructions and an appeal to chip in by taking over the hosting for certain regions? I think that this is possible (and then of course executed) was your plan anyway, wasn't it?

**Comment by westnordost** [comment]
Btw, I also get this:
`Error for URL request 'https://tiles.map-data.de/vector/v1/512/all/12/2260/1401.mvt': com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate expired at Fri Feb 22 23:02:01 GMT+01:00 2019 (compared to Mon Mar 04 17:49:09 GMT+01:00 2019)`

**Comment by rugk** [comment]
It sometimes felt like the same issue happened in Germany, too… So maybe regenerate there, too?

**Comment by Akasch** [comment]
@Rudloff the import has finally finished, it should work now.

This have taken quite a bit longer than I thought it would, the differences between SSD and HDD are big...

@westnordost yes, but i will need some more days to handle some cases and automate it more. The error you are seeing should not impact the App users, as it is falling back to the other fronted server immediately but i am on it to get the cert replaced.

@rugk i do not see any more of this kind of error in my logs, I need the region/tile on layer 5 or 6 to look into it.

**Comment by Rudloff** [comment]
It now works for some tiles, but I still get some 500 or 502 errors on around half the tiles:
```
03-05 13:17:21.740  6114 10062 D Tangram : ERROR networkDataSource.cpp:70: Error for URL request 'https://tiles.map-data.de/vector/v1/512/all/15/16661/11022.mvt': INTERNAL SERVER ERROR
03-05 13:17:21.741  6114 10062 D OkHttp  : Callback failure for call to https://tiles.map-data.de/...
03-05 13:17:21.741  6114 10062 D OkHttp  : java.io.IOException: Unexpected response code: Response{protocol=http/1.1, code=500, message=INTERNAL SERVER ERROR, url=https://tiles.map-data.de/vector/v1/512/all/15/16661/11022.mvt?api_key=null} for URL: https://tiles.map-data.de/vector/v1/512/all/15/16661/11022.mvt
03-05 13:17:21.741  6114 10062 D OkHttp  : 	at com.mapzen.tangram.MapController$13.onResponse(MapController.java:1388)
03-05 13:17:21.741  6114 10062 D OkHttp  : 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
03-05 13:17:21.741  6114 10062 D OkHttp  : 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-05 13:17:21.741  6114 10062 D OkHttp  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-05 13:17:21.741  6114 10062 D OkHttp  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-05 13:17:21.741  6114 10062 D OkHttp  : 	at java.lang.Thread.run(Thread.java:761)
03-05 13:17:21.766  6114 10060 D Tangram : ERROR networkDataSource.cpp:70: Error for URL request 'https://tiles.map-data.de/vector/v1/512/all/15/16661/11021.mvt': INTERNAL SERVER ERROR
03-05 13:17:21.767  6114 10060 D OkHttp  : Callback failure for call to https://tiles.map-data.de/...
03-05 13:17:21.767  6114 10060 D OkHttp  : java.io.IOException: Unexpected response code: Response{protocol=http/1.1, code=500, message=INTERNAL SERVER ERROR, url=https://tiles.map-data.de/vector/v1/512/all/15/16661/11021.mvt?api_key=null} for URL: https://tiles.map-data.de/vector/v1/512/all/15/16661/11021.mvt
03-05 13:17:21.767  6114 10060 D OkHttp  : 	at com.mapzen.tangram.MapController$13.onResponse(MapController.java:1388)
03-05 13:17:21.767  6114 10060 D OkHttp  : 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
03-05 13:17:21.767  6114 10060 D OkHttp  : 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-05 13:17:21.769  6114 10060 D OkHttp  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-05 13:17:21.769  6114 10060 D OkHttp  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-05 13:17:21.769  6114 10060 D OkHttp  : 	at java.lang.Thread.run(Thread.java:761)
03-05 13:17:21.845  6114 10061 D Tangram : ERROR networkDataSource.cpp:70: Error for URL request 'https://tiles.map-data.de/vector/v1/512/all/15/16660/11021.mvt': Bad Gateway
03-05 13:17:21.846  6114 10061 D OkHttp  : Callback failure for call to https://tiles.map-data.de/...
03-05 13:17:21.846  6114 10061 D OkHttp  : java.io.IOException: Unexpected response code: Response{protocol=http/1.1, code=502, message=Bad Gateway, url=https://tiles.map-data.de/vector/v1/512/all/15/16660/11021.mvt?api_key=null} for URL: https://tiles.map-data.de/vector/v1/512/all/15/16660/11021.mvt
03-05 13:17:21.846  6114 10061 D OkHttp  : 	at com.mapzen.tangram.MapController$13.onResponse(MapController.java:1388)
03-05 13:17:21.846  6114 10061 D OkHttp  : 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
03-05 13:17:21.846  6114 10061 D OkHttp  : 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-05 13:17:21.846  6114 10061 D OkHttp  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-05 13:17:21.846  6114 10061 D OkHttp  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-05 13:17:21.846  6114 10061 D OkHttp  : 	at java.lang.Thread.run(Thread.java:761)
03-05 13:17:21.886  6114 10065 D Tangram : ERROR networkDataSource.cpp:70: Error for URL request 'https://tiles.map-data.de/vector/v1/512/all/15/16660/11022.mvt': Bad Gateway
03-05 13:17:21.887  6114 10065 D OkHttp  : Callback failure for call to https://tiles.map-data.de/...
03-05 13:17:21.887  6114 10065 D OkHttp  : java.io.IOException: Unexpected response code: Response{protocol=http/1.1, code=502, message=Bad Gateway, url=https://tiles.map-data.de/vector/v1/512/all/15/16660/11022.mvt?api_key=null} for URL: https://tiles.map-data.de/vector/v1/512/all/15/16660/11022.mvt
03-05 13:17:21.887  6114 10065 D OkHttp  : 	at com.mapzen.tangram.MapController$13.onResponse(MapController.java:1388)
03-05 13:17:21.887  6114 10065 D OkHttp  : 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
03-05 13:17:21.887  6114 10065 D OkHttp  : 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-05 13:17:21.887  6114 10065 D OkHttp  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-05 13:17:21.887  6114 10065 D OkHttp  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-05 13:17:21.887  6114 10065 D OkHttp  : 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by Akasch** [comment]
Ok should be fixed, the 500 was from cache (as the server was not reached (502) and the 502 because my update script had an error in the restarting part

**Comment by Rudloff** [comment]
It now works correctly, thank you!

**Comment by westnordost** [comment]
@akasch The error I pasted is from an Android device

Am 5. März 2019 12:46:28 MEZ schrieb Nils Rokita <notifications@github.com>:
>@Rudloff the import has finally finished, it should work now.
>
>This have taken quite a bit longer than I thought it would, the
>differences between SSD and HDD are big...
>
>@westnordost yes, but i will need some more days to handle some cases
>and automate it more. The error you are seeing should not impact the
>App users, as it is falling back to the other fronted server
>immediately but i am on it to get the cert replaced.
>
>@rugk i do not see any more of this kind of error in my logs, I need
>the region/tile on layer 5 or 6 to look into it.
