### ISSUE TITLE
Stats syncronization

### ISSUE THREAD

**Issue by massimostanzione** [westnordost/StreetComplete#2323]
Hi, I use SC v26.2 on Android 7.1.1, logged in with my OSM account. Seven days ago I accidentally clicked "logout" (suggestion: a confirmation alert would be useful :smile:) and, when logged in again, the star count was reset to zero, with a "Your stats are syncing, please check again later" message into the statistics view. Seven days are passed and the situation is the same, even logging out/in again.
I checked into other similar issues, and in particular I don't know if is just the slow server (https://github.com/westnordost/StreetComplete/issues/2246#issuecomment-723472026) or maybe other kind of problems.
_This is my first public issue sumbit, so any suggestion on how to improve issue submitting is welcome!_

**Versions affected**
Android 7.1.1, SC v26.2

**Comment by westnordost** [comment]
Can you tell me your OSM user name or id?

**Comment by massimostanzione** [comment]
uid=717514
(By the way, if I change the username - sooner or later I'll do it - is it synchronized with SC through the uid?)

**Comment by westnordost** [comment]
yes

**Comment by westnordost** [comment]
Why did you change your username for practically every changeset you do?

**Comment by westnordost** [comment]
ok should be solved now

**Comment by massimostanzione** [comment]
Not yet at the moment, tried also forcing application stop, clearing cache and logout/login

**Comment by massimostanzione** [comment]
Update: upgrading to v27.0 (also uninstalling and re-downloading app) seems still not effective

**Comment by westnordost** [comment]
Hm. The problem in the backend is solved. 

The statistics returned for user 717514 are

```json
{
  "questTypes": {
    "AddBenchStatusOnBusStop": 7,
    "AddBuildingLevels": 2,
    "AddBuildingType": 4,
    "AddBusStopShelter": 13,
    "AddCrossingIsland": 12,
    "AddCrossingType": 2,
    "AddCycleway": 16,
    "AddHandrail": 1,
    "AddParkingAccess": 21,
    "AddParkingFee": 5,
    "AddParkingType": 3,
    "AddPathSurface": 5,
    "AddRailwayCrossingBarrier": 1,
    "AddRoadSurface": 19,
    "AddSidewalk": 2,
    "AddStepsIncline": 1,
    "AddStepsRamp": 2,
    "AddTrafficSignalsSound": 3,
    "AddTrafficSignalsVibration": 3,
    "AddWayLit": 11,
    "AddWheelchairAccessPublicTransport": 1
  },
  "countries": {
    "IT": 134
  },
  "daysActive": 1,
  "rank": null,
  "countryRanks": [],
  "lastUpdate": "2020-11-28T18:14:45+00:00",
  "isAnalyzing": false
}
```

The app will accept this and update it locally if `isAnalyzing` is false.

Can you look at the log? You need Android Studio or at least `adb` to be installed for that.

**Comment by massimostanzione** [comment]
Yes, these statistics should be right.
Found this in the log:
```
2020-11-28 19:39:45.943 30918-30947/? W/StatisticsUpdater: Unable to download statistics
    org.json.JSONException: Value [] at countryRanks of type org.json.JSONArray cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:100)
        at org.json.JSONObject.getJSONObject(JSONObject.java:613)
        at de.westnordost.streetcomplete.data.user.StatisticsDownloader.parse(StatisticsDownloader.kt:48)
        at de.westnordost.streetcomplete.data.user.StatisticsDownloader.download(StatisticsDownloader.kt:25)
        at de.westnordost.streetcomplete.data.user.StatisticsUpdater.updateFromBackend(StatisticsUpdater.kt:64)
        at de.westnordost.streetcomplete.data.user.UserController$updateStatistics$1.invokeSuspend(UserController.kt:74)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by westnordost** [comment]
Oh! Thank you.

And does it work now?

**Comment by massimostanzione** [comment]
Not yet, but slightly different warning:
```
2020-11-28 20:31:24.653 6402-6432/? W/StatisticsUpdater: Unable to download statistics
    org.json.JSONException: Value null at rank of type org.json.JSONObject$1 cannot be converted to int
        at org.json.JSON.typeMismatch(JSON.java:100)
        at org.json.JSONObject.getInt(JSONObject.java:481)
        at de.westnordost.streetcomplete.data.user.StatisticsDownloader.parse(StatisticsDownloader.kt:54)
        at de.westnordost.streetcomplete.data.user.StatisticsDownloader.download(StatisticsDownloader.kt:25)
        at de.westnordost.streetcomplete.data.user.StatisticsUpdater.updateFromBackend(StatisticsUpdater.kt:64)
        at de.westnordost.streetcomplete.data.user.UserController$updateStatistics$1.invokeSuspend(UserController.kt:74)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by westnordost** [comment]
Damn, and now?

**Comment by massimostanzione** [comment]
Now it works! Thank you.
