### ISSUE TITLE
V4.0 beta - quest icons showing as black squares 

### ISSUE THREAD

**Issue by DaCor1** [westnordost/StreetComplete#850]
Android 8.0.0
HTC 10

Just after updating the app 

![screenshot_20180209-221210](https://user-images.githubusercontent.com/4098779/36048224-2f0f1186-0de7-11e8-9532-583a662fe469.png)

**Comment by ENT8R** [comment]
I can repoduce this too... But not just since this version... Restarting the app might help to solve the issue temporarily for you...

**Comment by DaCor1** [comment]
Restart sorted it, cheers

**Comment by rugk** [comment]
Anyway, what was the reason for that? Was ist the first start of the app after the update?

**Comment by DaCor1** [comment]
For me it was.

I'll do a few more restarts, reboots to see if it reoccurs

**Comment by westnordost** [comment]
Theoretically, this bug may occur if a scene update is triggered and tangram-ES calls `onSceneReady` on
 the listener before the quest graphics finished initializing.
However, the quest graphics are created *synchronously* before loading the scene and the scene updates associated with loading the quest graphics are <a href="https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/tangram/QuestsMapFragment.java#L129">committed together with loading the actual map, also synchronously</a>. So, I don't see any way how StreetComplete can trigger a scene update before the quest graphics are loaded.
I suspect a bug in tangram-ES, but the problem is not reproducable enough that I am willing to create a bug over there. So, let's monitor this issue.

**Comment by RubenKelevra** [comment]
I often switch back to this app and no icons appear, moving the map just a little bit seems to trigger a redraw and all icons reappear on the map. Not a big deal, but might be the same bug, just that the drawing engine react slightly different - in my case they are just opaque and in his case black.

**Comment by ENT8R** [comment]
I think yours (@RubenKelevra) issue might be #724 or maybe #437

**Comment by ENT8R** [comment]
And the initial issue can't be fixed by moving the map AFAIK...

**Comment by RubenKelevra** [comment]
@ENT8R yeah, sounds more like #437 to me, but this ticket is already closed. I think it's not that big of a deal, but you might still want to escalate this?

**Comment by rugk** [comment]
Could also reproduce this at the very first start after the update to 4.0. The map could be moved and it were really the quest icons, which always were black. One restart and it is fixed.

**Comment by lenod** [comment]
I can reproduce this on android 7.1.2, on a new SC install (4.0).
A restart of the app or the phone does not fix this.
The icons have appeared at some point but this is an exception.
This may have to do with the fact that the phone is rather old and has rather low memory (1.5GB RAM).

**Comment by lenod** [comment]
Note: forcing GPU rendering of 2D objects in android developers options seems to fix the issue for me.

**Comment by lenod** [comment]
Correction: it doesn't.

**Comment by rugk** [comment]
I also experience this, e.g., when SC first crashes for some reason and then, at the next start, this issue happens.

**Comment by rugk** [comment]
BTW, could just reproduce this with a fresh installation of v 6b78a575fe4fb9f61652b3239be3a2a6060b90e7. LineageOS 14.1

After some time of using it and going into some menus (settings etc.) the issue just disappeared.

**Comment by rugk** [comment]
I've noticed that before the app may show these black things, it hides all quest icons, i.e.
1. quest icons are hidden, restart app (swipe out of recently used apps and start again)
2. black squares, restart
3. everything works again

**Comment by dbdean** [comment]
This seems to be happening a lot more for me lately, and it can sometimes take many closes and restarts of StreetComplete for it to come good.

**Comment by westnordost** [comment]
Hmm, I was about to create a ticket in tangram-es after all, but while having another look at the code to describe a reproduction, I found a possible race condition when creating the icons bitmap:

For a faster startup, a background thread starts creating the icons bitmap on application start (takes about 0.8 seconds on my phone). Then shortly after, when the map is being initialized (about 0.6 seconds after application start), the main thread is supposed to wait for that background thread to finish creating the bitmap, saving it to disk and then use it.

What actually happens, though, is that the main thread ignores this and always creates its own bitmap. Now I am not sure what constellation of two threads competing to save bitmap to the same file on disk may result in no/completely black bitmap to be loaded, but that behavior was definitely wrong, so likely the cause. If not the cause, then at least the startup will be about 0.6 seconds faster.
The specific mistake was that the class which creates this bitmap was not used as a singleton.

**Comment by westnordost** [comment]
In other words, I will close this, feel free to reopen it in case it still happens with the upcoming v8.2.
